/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Nicolas_2
 */
public class SystemMonitor extends javax.swing.JFrame {

    /**
     * Creates new form SystemMonitor
     */
    public SystemMonitor() {
        initComponents();

        ImageIcon image = new ImageIcon("ImageLibrary/feu_rouge.jpg");
        JLabel label = new JLabel("", image, JLabel.CENTER);
        lightsPanel.add(label, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        leverPanel = new javax.swing.JPanel();
        lightsPanel = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        wheelsPanel = new javax.swing.JPanel();
        doorsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jSplitPane1.setDividerLocation(400);

        jSplitPane2.setDividerLocation(300);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout leverPanelLayout = new javax.swing.GroupLayout(leverPanel);
        leverPanel.setLayout(leverPanelLayout);
        leverPanelLayout.setHorizontalGroup(
            leverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        leverPanelLayout.setVerticalGroup(
            leverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jSplitPane2.setTopComponent(leverPanel);

        javax.swing.GroupLayout lightsPanelLayout = new javax.swing.GroupLayout(lightsPanel);
        lightsPanel.setLayout(lightsPanelLayout);
        lightsPanelLayout.setHorizontalGroup(
            lightsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        lightsPanelLayout.setVerticalGroup(
            lightsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(lightsPanel);

        jSplitPane1.setLeftComponent(jSplitPane2);

        jSplitPane3.setDividerLocation(300);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout wheelsPanelLayout = new javax.swing.GroupLayout(wheelsPanel);
        wheelsPanel.setLayout(wheelsPanelLayout);
        wheelsPanelLayout.setHorizontalGroup(
            wheelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        wheelsPanelLayout.setVerticalGroup(
            wheelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jSplitPane3.setTopComponent(wheelsPanel);

        javax.swing.GroupLayout doorsPanelLayout = new javax.swing.GroupLayout(doorsPanel);
        doorsPanel.setLayout(doorsPanelLayout);
        doorsPanelLayout.setHorizontalGroup(
            doorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        doorsPanelLayout.setVerticalGroup(
            doorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(doorsPanel);

        jSplitPane1.setRightComponent(jSplitPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel doorsPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JPanel leverPanel;
    private javax.swing.JPanel lightsPanel;
    private javax.swing.JPanel wheelsPanel;
    // End of variables declaration//GEN-END:variables
}
